<a href="https://colab.research.google.com/github/ritulsh29/Python-for-Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy=Numerical Python

In [ ]:
#Single-dimensional Array
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#Multidimensional array
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [ ]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [ ]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
n1=np.arange(10,50,5) #10 to 49 with step of 5.

In [ ]:
n1=np.random.randint(1,100,5)
n1

array([32, 90, 20, 85, 62])

In [ ]:
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [ ]:
n1.shape=(3,2)
n1.shape

(3, 2)

In [ ]:
l1=[10,20,30]
l2=[40,50,60]
n1=np.array(l1)
n2=np.array(l2)
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
l1=[10,20,30]
l2=[40,50,60]
n1=np.array(l1)
n2=np.array(l2)
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [ ]:
l1=[10,20,30]
l2=[40,50,60]
n1=np.array(l1)
n2=np.array(l2)
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
l1=[10,20,30,40]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
np.setdiff1d(n1,n2)

array([30, 40])

In [ ]:
l1=[10,20,30,40]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
np.setdiff1d(n2,n1)

array([60])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
np.intersect1d(n1,n2)

array([10, 20])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
np.sum([n1,n2])

150

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
np.sum([n1,n2], axis=0) #adds columns.

array([20, 40, 90])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
np.sum([n1,n2], axis=1)

array([60, 90])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
n1=n1+1
n1

array([11, 21, 31])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
n1=n1-1
n1

array([ 9, 19, 29])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
n1=n1*2
n1

array([20, 40, 60])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
n1=n1/2
n1

array([ 5., 10., 15.])

In [ ]:
l1=[10,20,30]
l2=[10,20,60]
n1=np.array(l1)
n2=np.array(l2)
n1=n1%2
n1

array([0, 0, 0])

In [ ]:
l1=[10,20,30]
n1=np.array(l1)
np.mean(n1)

20.0

In [ ]:
l1=[10,20,30,24]
n1=np.array(l1)
np.median(n1)

22.0

In [ ]:
l1=[10,20,30]
n1=np.array(l1)
np.std(n1)

8.16496580927726

In [ ]:
l1=[10,20,30]
n1=np.array(l1)
np.save('my_numpy',n1)

In [ ]:
n2=np.load('my_numpy.npy')
n2

array([10, 20, 30])